Polinabinder/scdl document
NVIDIA/bionemo-framework pull request #390
Opened 2024-10-31 23:09 UTC by polinabinder1

I'm adding a few changes to the SCDL documentation to make it a bit more clear. I am also adding explanation of the paginated loading.

2024-11-01 17:49 UTC, malcolmgreaves approved these changes

2024-11-01 19:01 UTC, trvachov requested changes
Good update. I just had font/capitalization feedback.

2024-11-05 17:31 UTC, polinabinder1 commented on sub-packages/bionemo-scdl/README.md
> +BioNemo-SCDL provides an independent pytorch-compatible dataset class for single cell data with a consistent API. BioNemo-SCDL is developed and maintained by NVIDIA. This package can be run independe
Done

2024-11-07 18:05 UTC, trvachov approved these changes

2024-11-07 18:14 UTC, merged