Sichu/limit val batches=0p0
NVIDIA/bionemo-framework pull request #492
Opened 2024-12-03 14:12 UTC by sichu2023

## Summary
Allow `--limit-val-batches=0.` to disable validation. Same applies for testing in geneformer.

## Details
Previously validation dataset cannot be created when `limit_val_batches = 0.`. Now this is caught and the validation dataset is set to `None`. Same applies to test dataset.

2024-12-03 14:15 UTC, sichu2023 commented
/build-ci

2024-12-03 14:52 UTC, jstjohn approved these changes
Can you also add a test to lock in this support?

2024-12-03 15:20 UTC, sichu2023 commented
> Can you also add a test to lock in this support?

Will do. Just disabled auto-merge.

2024-12-03 15:39 UTC, farhadrgh requested changes
Would you add this support to infer/fintetune datamodule [here](https://github.com/NVIDIA/bionemo-framework/blob/main/sub-packages/bionemo-esm2/src/bionemo/esm2/model/finetune/datamodule.py) as well?

2024-12-04 14:53 UTC, sichu2023 commented
/build-ci

2024-12-04 15:18 UTC, sichu2023 commented
> Would you add this support to infer/fintetune datamodule [here](https://github.com/NVIDIA/bionemo-framework/blob/main/sub-packages/bionemo-esm2/src/bionemo/esm2/model/finetune/datamodule.py) as well?

Done!

2024-12-04 16:11 UTC, farhadrgh approved these changes

2024-12-04 17:09 UTC, pstjohn approved these changes

2024-12-04 17:09 UTC, pstjohn commented on sub-packages/bionemo-geneformer/tests/bionemo/geneformer/scripts/test_train_geneformer.py
> -def test_main_runs(tmpdir):
can we make sure this is running a super small version of the model? Any other CLI options we can change to make this run as fast as possible would be great.

2024-12-04 20:39 UTC, sichu2023 commented
/build-ci

2024-12-05 12:29 UTC, sichu2023 commented
/build-ci

2024-12-12 08:59 UTC, sichu2023 commented
/build-ci

2024-12-12 10:07 UTC, merged